title: ĞšĞ¾Ğ»Ğ»ĞµĞºÑ†Ğ¸Ñ Emoji ğŸŒ Ğ´Ğ»Ñ Markdown
description: ĞšĞ¾Ğ»Ğ»ĞµĞºÑ†Ğ¸Ñ Emoji ğŸŒ Ğ´Ğ»Ñ Markdown
remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-sitemap
  - jemoji
  - jekyll-mentions
paginate: 5
collections:
  categories:
    output: true
